### ISSUE TITLE
Probably my fault

### ISSUE THREAD

**Issue by Oman395** [SolraBizna/logi6502#5]
Hey, somewhat new to this so it's probably my fault, but when outputting data through STA, rather than getting clean 0/1, I'm getting floating 0/floating. Is that intentional, and am I doing something wrong? Thanks!
Heres my setup ATM
![why](https://user-images.githubusercontent.com/77183348/145632441-5c77da2e-42df-4508-9d80-c50bfcad9048.png) Broken output
![rom](https://user-images.githubusercontent.com/77183348/145632462-6e05d76a-ff43-49f8-8af4-64bb1094412c.png) ROM as it is when instruction happens
![ram](https://user-images.githubusercontent.com/77183348/145633185-c747faa7-f31d-4d77-8b90-1e6a4c9b289b.png) RAM if it helps
![whole](https://user-images.githubusercontent.com/77183348/145633200-98863015-7a47-4c28-9a93-5a7381551a83.png) Complete circuit

**Comment by SolraBizna** [comment]
It looks like you've got the `ld` input to the RAM backwards. `RWB#` will be low for a write cycle and high for a read cycle, which is already how Logisim's RAM component wants it. Remove the inverter on the `ld` and it should behave. Though, depending on what version of Logisim you're using, you might need to invert the clock input to the RAM. (The community fork allows you to select which edge the RAM is clocked on, whereas the original only supports what the 6502 would think of as the "wrong edge".)

For the record, the red color of the D lines indicates a conflict (`X`), and means the D lines are being driven by multiple, disagreeing sources; in this case, the CPU is driving the data it wants to write, but the RAM thinks it's a read cycle so it's driving some data of its own. If they were floating (`Z`), they would have been blue.

I hope this gets you where you need to go.

**Comment by Oman395** [comment]
Thanks man! Helped out a lot, got it working now :D thought the ram was opposite, probably should have checked logisim Docs. Oh well! Thanks again!

**Comment by SolraBizna** [comment]
My usual strategy with the clock and `ld` pins is "add and remove inverters until it behaves". Don't tell my boss. :)

I'm glad you got it working, and I'd be interested in seeing what you end up with.

**Comment by Oman395** [comment]
Mostly just messing around tbh, want to get a feel for the 6502 before I actually make it IRL-- got a simple counter working tho, thats pretty fun :D
