### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Emil-DV** [SolraBizna/logi6502#6]
I'd like to get this running under the latest version of Logisim-evolution and I was wondering if you had put together a set of build instructions.  I found that this has an Intelij project so I brought it up in that but of course it is missing some of the logisim sources.  Was this meant to be placed into the same location as the logisim sources or was it a stand alone project with those sources copied over?

**Comment by SolraBizna** [comment]
I don't remember how to build it, unfortunately. It's been too long. I vaguely remember having to specify a path to a Logisim source jar at some point.

I actually recently discovered that this doesn't work in Logisim-evolution myself (while a student was watching, ouch). I thought about dusting it off and trying to port it, and maybe also fixing the bug where the "expert" part puts itself to sleep forever the first time it executes `WAI`, and applying the stuff I learned from 65test to make it truly cycle- and signal-accurate... Unfortunately, I just have so little time lately...

**Comment by Emil-DV** [comment]
I ended up installing Intellij and the project came up just fine.  I then pointed to the newly built Logisim-evolution .jar file and only had to make a couple of changes (readportvalue vs. readport & new abstract function) to get it to install okay.  There were then a few changes to the example circuit (buffers vs. transistors & changes in the RAM/ROM objects - no select lines).  The changes are in my branch located here: https://github.com/Emil-DV/logi6502/tree/LogisimEvolution35+

I'm not sure how the .lua files are part of the build if they were called by Intellij or if they would have to be run separately but so far it appears to be working.

**Comment by SolraBizna** [comment]
> I ended up installing Intellij and the project came up just fine. I then pointed to the newly built Logisim-evolution .jar file and only had to make a couple of changes (readportvalue vs. readport & new abstract function) to get it to install okay. There were then a few changes to the example circuit (buffers vs. transistors & changes in the RAM/ROM objects - no select lines). The changes are in my branch located here: https://github.com/Emil-DV/logi6502/tree/LogisimEvolution35+

Excellent! Are these changes backwards compatible with vanilla Logisim?

> I'm not sure how the .lua files are part of the build if they were called by Intellij or if they would have to be run separately but so far it appears to be working.

They're used to autogenerate parts of the emulator core, but you only need them if you're making changes to the emulator.

**Comment by Emil-DV** [comment]
Unfortunately the changes are not backwards compatible with vanilla logisim as they are changes in the function/method signatures.

**Comment by SolraBizna** [comment]
I thought as much. That's a shame.

Thanks for your changes. They are indeed quite simple.  I'll have to try to figure out some way to build two versions, one for Logisim and one for Logisim-evolution...

**Comment by SolraBizna** [comment]
I have integrated Logisim Evolution support, including an updated example circuit. More related to the original title of this issue (heh), I have added build instructions to the README. Thank you again for your initiative!
