### ISSUE TITLE
Cant import or open demo.

### ISSUE THREAD

**Issue by ghost** [SolraBizna/logi6502#7]
For some reason, Logisim 2.7.1 AND Logisim-Evolution 4.0.4 both refuse to import the library or open the demos. The demo locks up at Loading File both of them.

**Comment by SolraBizna** [comment]
I encountered that problem only when I tried to launch (original) Logisim directly into the demo circuit, and then only if it needed to prompt for the location of the library. Otherwise, that doesn't reproduce at my end.

What operating system are you on, and what Java runtime are you using?

**Comment by ghost** [comment]
Running Windows 11 Version 10.0.22000 Build 22000. I have another Windows 11 laptop that runs it perfectly.

"java -version" says:
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

**Comment by ghost** [comment]
Just updated java, now -version says:
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing

Still wont work after an update.

**Comment by SolraBizna** [comment]
Out of curiosity, do these jars load fine?
[logi6502-maybefixed.zip](https://github.com/SolraBizna/logi6502/files/8319350/logi6502-maybefixed.zip)

**Comment by ghost** [comment]
Yes, worked fine. Can import and open one demo with those jars. The evolution demo crashed upon opening it. Thanks!

**Comment by SolraBizna** [comment]
If the evolution demo crashes on opening, then we haven't completely fixed it. And the Evolution version of Logisim is mostly superior, so I'd like people to be able to use it.

Though it crashes on opening the demo, does Evolution successfully import the jar at least? And, what if you try it with a slightly older version of Evolution? (I tested against 3.7.1)
