### ISSUE TITLE
wrong starting address in PDIP version

### ISSUE THREAD

**Issue by Musickiller** [SolraBizna/logi6502#8]
Hi!

The evolution PDIP version starts with 7AEA if it's been asked to start reading the rom with EAEA. I don't think that's correct o_O

The setup:
![image](https://user-images.githubusercontent.com/10563011/210899583-fb914cb0-1457-4727-ad0a-c826c5f80bdc.png)

"ROM" 😂
![image](https://user-images.githubusercontent.com/10563011/210899615-a0a598a9-5aa1-4b0a-ba05-e74cc26db7d9.png)

The same setup works great for other two cirquits for some reason o_O

**Comment by Musickiller** [comment]
Sorry, I think I found it. I've accidentally misplaced A12..A15. Small numbers, deep night. Sorry to bother!

edit:
correct version:
![image](https://user-images.githubusercontent.com/10563011/210900438-66ccb603-2545-4563-8ae8-f8fff2f65174.png)

**Comment by SolraBizna** [comment]
Happens to all of us. (We can blame WDC for the pin placement.)

Cheers!
